# Generated by Django 4.0.5 on 2022-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='summary',
            field=models.TextField(help_text='Da una breve descripcion de la Pelicula', max_length=350),
        ),
    ]
